### ISSUE TITLE
What kind of url do you pass in?

### ISSUE THREAD

**Issue by dylanjha** [sillypog/google-spreadsheet-util#1]
I'm currently trying this:
`"https://docs.google.com/spreadsheet/pub?key=0AsMGn_2Fl4CEdG1sQ1VtemtnZHRDT3pna1RzR0R6Q3c&output=html"`

but I feel like I want a JSON format or something.  Think you provide an example url?

Just realize it needed format=csv.  You can close this issue thanks!
`https://docs.google.com/spreadsheet/pub?key=0AsMGn_2Fl4CEdG1sQ1VtemtnZHRDT3pna1RzR0R6Q3c&output=csv`

**Comment by sillypog** [comment]
Hi Dylan,

Thanks for taking a look at this repo. I'm sorry I didn't get an answer to
you over the weekend. It looks like you figured it out though; it is
designed to work with the CSV version of the spreadsheet.

Thanks for your pull request, much appreciated :-)

Cheers,
Pete

**Comment by dylanjha** [comment]
thank you!

:beers:
